import { CitizenUser, StaffUser, Booking, Complaint } from './types';

export const INITIAL_CITIZEN: CitizenUser = {
  id: 'cit-101',
  fullName: 'Yashna A',
  rationCardNumber: '123456789',
  mobileNumber: '98765xxxxx',
  cardType: 'priority',
  shopArea: 'Velachery 04',
  avatarUrl: 'https://img.favpng.com/3/11/24/3d-woman-avatar-stylized-cartoon-woman-avatar-with-glasses-g0FutwYY.jpg',
  quotaUsed: true,
};

export const INITIAL_STAFF: StaffUser = {
  id: 'stf-201',
  fullName: 'Arun',
  employeeId: 'EMP-99823',
  mobileNumber: '98765xxxxx',
  shopArea: 'Velachery 04',
  avatarUrl: 'https://c8.alamy.com/comp/2ER1F36/cute-cartoon-character-holding-id-badge-and-waving-hello-new-employee-at-work-funny-office-staff-drawing-vector-illustration-2ER1F36.jpg',
};

export const INITIAL_BOOKINGS: Booking[] = [
  {
    id: 'b-1',
    referenceId: '#PDS-88291',
    citizenId: 'cit-101',
    citizenName: 'Rakshanna',
    type: 'home_delivery',
    status: 'COMPLETED',
    date: 'Oct 24, 2023',
    timeSlot: 'Morning (9:00 AM - 11:00 AM)',
    fpsCenter: 'Zonal Center 04',
    amount: 0,
    otp: '4892',
    createdAt: '2023-10-24T09:00:00Z',
  },
  {
    id: 'b-2',
    referenceId: '#PDS-90124',
    citizenId: 'cit-101',
    citizenName: 'Yashna A',
    type: 'in_person',
    status: 'COMPLETED',
    date: 'Jun 15, 2026',
    timeSlot: '10:30 AM - 11:00 AM',
    fpsCenter: 'Velachery Shop #04',
    amount: 0,
    otp: '7301',
    createdAt: '2023-11-01T10:00:00Z',
  },
  {
    id: 'b-3',
    referenceId: '#PDS-77421',
    citizenId: 'cit-101',
    citizenName: 'Rakshanna',
    type: 'home_delivery',
    status: 'CANCELLED',
    date: 'Oct 15, 2023',
    timeSlot: 'Afternoon (12:00 PM - 2:00 PM)',
    fpsCenter: 'Zonal Center 04',
    amount: 0,
    reason: 'Incomplete Address',
    createdAt: '2023-10-15T12:00:00Z',
  },
  {
    id: 'b-4',
    referenceId: '#PDS-65239',
    citizenId: 'cit-101',
    citizenName: 'Rakshanna',
    type: 'home_delivery',
    status: 'COMPLETED',
    date: 'Sep 28, 2023',
    timeSlot: 'Evening (3:00 PM - 5:00 PM)',
    fpsCenter: 'Main Station 01',
    amount: 0,
    otp: '1294',
    createdAt: '2023-09-28T15:00:00Z',
  },
];

export const INITIAL_COMPLAINTS: Complaint[] = [
  {
    id: 'c-1',
    trackingId: 'PDS-2023-88421',
    citizenId: 'cit-101',
    citizenName: 'Monika',
    shopArea: 'Velachery 04',
    category: 'quality',
    categoryLabel: 'Quality Issue (Food Grains)',
    description: 'Grain quality received in the last batch had small stones.',
    status: 'PENDING',
    createdAt: '2023-11-02T11:20:00Z',
  },
  {
    id: 'c-2',
    trackingId: 'PDS-2023-74112',
    citizenId: 'cit-102',
    citizenName: 'Rakshanna',
    shopArea: 'Velachery 04',
    category: 'fps_closed',
    categoryLabel: 'FPS Shop Closed during hours',
    description: 'Shop was closed at 2 PM on Tuesday during working hours.',
    status: 'PENDING',
    createdAt: '2023-11-03T14:10:00Z',
  },
  {
    id: 'c-4',
    trackingId: 'PDS-2023-50021',
    citizenId: 'cit-104',
    citizenName: 'Reckshna',
    shopArea: 'Velachery 04',
    category: 'behavior',
    categoryLabel: 'Staff Behavior',
    description: 'Staff member was rude when asking for electronic weighing verification.',
    status: 'PENDING',
    createdAt: '2023-11-05T16:30:00Z',
  },
];

export const RATION_ENTITLEMENTS = [
  { item: 'Rice (Priority Card)', limit: '20 kg', price: 'Free' },
  { item: 'Wheat', limit: '10 kg', price: 'Free' },
  { item: 'Sugar', limit: '1 kg', price: '₹25 / kg' },
  { item: 'Toor Dal', limit: '1 kg', price: '₹30 / kg' },
  { item: 'Palm Oil', limit: '1 Liter', price: '₹25 / L' },
];
