import { CitizenUser, StaffUser, Booking, Complaint } from './types';

export const INITIAL_CITIZEN: CitizenUser = {
  id: 'cit-101',
  fullName: 'Rakshanna',
  rationCardNumber: '123456789',
  mobileNumber: '9876543210',
  cardType: 'priority',
  shopArea: 'Velachery 04',
  avatarUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAhPM8y3DXJrwCeHdsaO3yw8IEiu8_c6DtvPv7ddcnUY0CSaQ46MEKWnvND0rftgGmIyAkp7Vipw0mDbH83uXSmyqo_PP1wyEzLP4CNnnIMCTqvbzoX-WEYm-LoCGGrnwbxpJh-6xiBL-vTQY8er1tH4Y3l7Yycpv5WV45GUCxG5JJr77bHQLGF6QMXKgeYktTI50brGyz0mzNoTCUK8rsu2SUQ8XPxdtiAwIGFLYaJZBdjBeEDuXH0rjhkIiqmvoSzkjZourXlklWp',
  quotaUsed: true,
};

export const INITIAL_STAFF: StaffUser = {
  id: 'stf-201',
  fullName: 'Rajesh Kumar',
  employeeId: 'EMP-99823',
  mobileNumber: '9876543211',
  shopArea: 'Velachery 04',
  avatarUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAl7ZftlZmhEZBSkKsGm_UoOUpQk2VjIF5HvgCd_SaWi_eCvUKjAG9MSp7gBQEncymStp3MTlYApjpP3j-zRdnTPmCDW1UVtLCKH5U4jtWRgeznhkZD0ohd1taNaGD76FuyHk99isPlun02GNzSk3ZxdwB7fHZxOyg1I7bAZq2ksCY-OKSPWfeoweiBhnvBHhWdd9g8I8wYV8DxYpVOsdI45B1VJHUwAy9UiMpw6zaztl6AHfLnc081kFVjsBrKzKoztrgoOluwtFIl',
};

export const INITIAL_BOOKINGS: Booking[] = [
  {
    id: 'b-1',
    referenceId: '#PDS-88291',
    citizenId: 'cit-101',
    citizenName: 'Rakshanna',
    type: 'home_delivery',
    status: 'COMPLETED',
    date: 'Oct 24, 2023',
    timeSlot: 'Morning (9:00 AM - 11:00 AM)',
    fpsCenter: 'Zonal Center 04',
    amount: 0,
    otp: '4892',
    createdAt: '2023-10-24T09:00:00Z',
  },
  {
    id: 'b-2',
    referenceId: '#PDS-90124',
    citizenId: 'cit-101',
    citizenName: 'Rakshanna',
    type: 'in_person',
    status: 'SCHEDULED',
    date: 'Nov 12, 2023',
    timeSlot: '10:30 AM - 11:00 AM',
    fpsCenter: 'Velachery Shop #04',
    amount: 0,
    otp: '7301',
    createdAt: '2023-11-01T10:00:00Z',
  },
  {
    id: 'b-3',
    referenceId: '#PDS-77421',
    citizenId: 'cit-101',
    citizenName: 'Rakshanna',
    type: 'home_delivery',
    status: 'CANCELLED',
    date: 'Oct 15, 2023',
    timeSlot: 'Afternoon (12:00 PM - 2:00 PM)',
    fpsCenter: 'Zonal Center 04',
    amount: 0,
    reason: 'Incomplete Address',
    createdAt: '2023-10-15T12:00:00Z',
  },
  {
    id: 'b-4',
    referenceId: '#PDS-65239',
    citizenId: 'cit-101',
    citizenName: 'Rakshanna',
    type: 'home_delivery',
    status: 'COMPLETED',
    date: 'Sep 28, 2023',
    timeSlot: 'Evening (3:00 PM - 5:00 PM)',
    fpsCenter: 'Main Station 01',
    amount: 0,
    otp: '1294',
    createdAt: '2023-09-28T15:00:00Z',
  },
];

export const INITIAL_COMPLAINTS: Complaint[] = [
  {
    id: 'c-1',
    trackingId: 'PDS-2023-88421',
    citizenId: 'cit-101',
    citizenName: 'Rakshanna',
    shopArea: 'Velachery 04',
    category: 'quality',
    categoryLabel: 'Quality Issue (Food Grains)',
    description: 'Grain quality received in the last batch had small stones.',
    status: 'PENDING',
    createdAt: '2023-11-02T11:20:00Z',
  },
  {
    id: 'c-2',
    trackingId: 'PDS-2023-74112',
    citizenId: 'cit-102',
    citizenName: 'Karthik Raja',
    shopArea: 'Velachery 04',
    category: 'fps_closed',
    categoryLabel: 'FPS Shop Closed during hours',
    description: 'Shop was closed at 2 PM on Tuesday during working hours.',
    status: 'PENDING',
    createdAt: '2023-11-03T14:10:00Z',
  },
  {
    id: 'c-3',
    trackingId: 'PDS-2023-61109',
    citizenId: 'cit-103',
    citizenName: 'Suresh Babu',
    shopArea: 'Velachery 04',
    category: 'delivery',
    categoryLabel: 'Delayed Delivery',
    description: 'Home delivery slot selected was morning, but arrived at 6 PM.',
    status: 'PENDING',
    createdAt: '2023-11-04T09:45:00Z',
  },
  {
    id: 'c-4',
    trackingId: 'PDS-2023-50021',
    citizenId: 'cit-104',
    citizenName: 'Meenakshi Sundaram',
    shopArea: 'Velachery 04',
    category: 'behavior',
    categoryLabel: 'Staff Behavior',
    description: 'Staff member was rude when asking for electronic weighing verification.',
    status: 'PENDING',
    createdAt: '2023-11-05T16:30:00Z',
  },
];

export const RATION_ENTITLEMENTS = [
  { item: 'Rice (Priority Card)', limit: '20 kg', price: 'Free' },
  { item: 'Wheat', limit: '10 kg', price: 'Free' },
  { item: 'Sugar', limit: '1 kg', price: '₹25 / kg' },
  { item: 'Toor Dal', limit: '1 kg', price: '₹30 / kg' },
  { item: 'Palm Oil', limit: '1 Liter', price: '₹25 / L' },
];
